### PR TITLE
Add Thinkfree and clean out the last bits of GB in the build.prop

### PR DESCRIPTION
**Pull request by Stevespear426**
Just me being a bit anal and cleaning up....

### CODE REVIEW

**Comment by KhasMek** [comment]
It has references to the gingerbread build because it still uses proprietary files from it. These are here to assist when finding what release the blobs come from.

Also, IMO thinkfree isn't needed as it's not in any other AOKP build, but I'll let someone else decide that.

**Comment by Stevespear426** [comment]
It builds, boots, and runs fine. The reason I changed it was some peeps
were complaining about apps not working because it can't tell the device
it's on Ics. If you think this will not help don't worry about it...
On Mar 13, 2012 11:39 PM, "Khas&apos;Mek" <
reply@reply.github.com>
wrote:

**Comment by KhasMek** [comment]
If people are having issues with apps not detecting that it's an ICS build, it's due to "BUILD_ID=ICL53F". This can be changed to "BUILD_ID=IML74K". The rest should probably stay the way it is though.

**Comment by Stevespear426** [comment]
Ok disregard that commit please I'll send up one with that change tomorrow.
Thanks for the help.
On Mar 14, 2012 12:02 AM, "Khas&apos;Mek" <
reply@reply.github.com>
wrote:

**Comment by KhasMek** [comment]
Sounds good. I'll keep an eye out for the pull request.

**Comment by Stevespear426** [comment]
Hate to bug you about this but it seems Roman is very busy. Its there
anyway some one can take a look at the commits waiting in Romcontrol and
framework? I got a sweet volume options mod I want to pull request but git
won't let me until that one clears.
On Mar 14, 2012 12:06 AM, "Khas&apos;Mek" <
reply@reply.github.com>
wrote:

**Pull request closed without merging**
